services:
  postgres:
    image: public.ecr.aws/z9j8u5b3/instant-public:postgresql-16-pg-hint-plan
    ports:
      - '8890:5432'
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: instant
      POSTGRES_DB: instant
    volumes:
      - 'backend-db:/var/lib/postgresql/data'
    networks:
      - application
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "instant"]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=4"
      - "-c"
      - "max_wal_senders=4"
      - "-c"
      - "shared_preload_libraries=pg_hint_plan"
      - "-c"
      - "random_page_cost=1.1"

  server:
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: Dockerfile-dev
    environment:
      DATABASE_URL: "postgresql://instant:pass@postgres:5432/instant"
      NREPL_BIND_ADDRESS: "0.0.0.0"
    volumes:
      - './:/app'
    ports:
      - '8888:8888'
      - '6005:6005'
    networks:
      - application

networks:
  application:
    driver: bridge
volumes:
  backend-db:
